os:
    - linux
language: cpp
matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - qt*5-dev
            - libqt5svg5*
            - unrar
            - g++-6
            - gcc-6
script: ./build-unix.sh
