language: cpp
compiler:
	- gcc
	- clang
matrix:
  include:
    - os: linux
      env: PLATFORM=linux
      addons:
        apt:
          packages:
            - g++-6
            - gcc-6
			- clang++
			- clang
            - cmake
            - cmake-data
			- qt*5-dev
script:
	- mkdir build
	- cd build
	- cmake -DWITH_CLIENT=ON -DWITH_SERVER=ON -DWITH_TOOLS=ON -DWITH_TRANSLATOR=ON -DTEST_CONFIG=ON -DWITH_CONSOLE=OFF -DCMAKE_BUILD_TYPE=Release ..
	- make
	- cd bin
	- ./UnitTester