os:
    - linux
language: cpp
matrix:
  include:
    - os: linux
      compiler:
        - gcc
        - clang
      addons:
        apt:
          packages:
            - qt*5-dev
            - libqt5svg5*
script: ./build-unix.sh
