install:
# necessary exports for build scripts
- if [ "$CXX" = "g++" ]; then export SPINE_COMPILER="gcc"; fi
- if [ "$CXX" = "clang++" ]; then export SPINE_COMPILER="clang"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        - ubuntu-sdk-team
        packages:
        - gcc
        - g++
		- clang++
		- clang
        - qtdeclarative5-dev
os:
    - linux
language: cpp
compiler:
    - gcc
    - clang
script:
	- mkdir build
	- cd build
	- cmake -DWITH_CLIENT=ON -DWITH_SERVER=ON -DWITH_TOOLS=ON -DWITH_TRANSLATOR=ON -DWITH_CONSOLE=OFF -DTEST_CONFIG=ON -DCMAKE_BUILD_TYPE=Release ..
	- make
