os:
    - linux
language: cpp
compiler:
    - gcc
    - clang
matrix:
  include:
    - os: linux
      env: PLATFORM=linux
      addons:
        apt:
          packages:
            - qt*5-dev
script: ./build-unix.sh
