@echo OFF

SET DEP_DIR=%cd%
SET TMP_DIR=%cd%\tmp

IF "%1" == "downloadAndUnpack" (goto downloadAndUnpack)

IF [%1] == [msvc13] (
	SET VSCOMPILER=Visual Studio 12 2013
	SET BOOSTCOMPILER=msvc-12.0
	SET ARCH_DIR=msvc13_
	SET CONFIG_BAT_PATH="%VS12%"
)
IF [%1] == [msvc15] (
	SET VSCOMPILER=Visual Studio 14 2015
	SET BOOSTCOMPILER=msvc-14.0
	SET ARCH_DIR=msvc15_
	SET CONFIG_BAT_PATH="%VS15%"
)

IF [%2] == [32] (
	SET VSARCH=
	SET BOOSTARCH=32
	SET ARCH_DIR=%ARCH_DIR%32
	SET VSBATARCH=x86
	SET VSSOLUTIONARCH=Win32
)
IF [%2] == [64] (
	SET VSARCH=x64
	SET BOOSTARCH=64
	SET ARCH_DIR=%ARCH_DIR%64
	SET VSBATARCH=amd64
	SET VSSOLUTIONARCH=x64
)

IF [%CONFIG_BAT_PATH%] == [] EXIT /B

FOR %%X IN (MSBuild.exe) DO (SET FOUND=%%~$PATH:X)
IF NOT DEFINED FOUND (
	CALL %CONFIG_BAT_PATH% %VSBATARCH%
)

EXIT /B

:downloadAndUnpack

SET DOWNLOAD_URL=%4
IF [%4] == [] Set DOWNLOAD_URL=http://www.clockwork-origins.de/dependencies/
IF NOT EXIST %TMP_DIR% (mkdir %TMP_DIR%)
REM IF NOT EXIST %TMP_DIR%\%2 (bitsadmin /transfer "myDownloadJob%2" /download /priority normal %DOWNLOAD_URL%%2 %TMP_DIR%\%2)
pushd %TMP_DIR%

SETLOCAL EnableDelayedExpansion
SET DOWNLOADEDARCHIVE=%2

IF NOT EXIST %TMP_DIR%\%DOWNLOADEDARCHIVE% (curl -OL %DOWNLOAD_URL%%DOWNLOADEDARCHIVE% --output %DOWNLOADEDARCHIVE%)

echo "Downloaded %DOWNLOADEDARCHIVE%"

IF EXIST %3 RD /S /Q "%DOWNLOADEDARCHIVE%"
winrar.exe x -ibck %DOWNLOADEDARCHIVE%
IF NOT "%ERRORLEVEL%" == "0" (
	
	if "%%2:~-6%" neq "tar.gz" (
		echo "Trying unzip tar for %DOWNLOADEDARCHIVE%"
		SET NEXTDOWNLOADEDARCHIVE=!DOWNLOADEDARCHIVE:~0,-3!
		7z x %DOWNLOADEDARCHIVE%
		7z x !NEXTDOWNLOADEDARCHIVE!
	) else (
		echo "Trying unzip other for %DOWNLOADEDARCHIVE%"
		7z x %DOWNLOADEDARCHIVE%
	)
)
popd
IF NOT EXIST %3 EXIT /B
EXIT /B 0

